### ISSUE TITLE
Map marker flickers when panning map

### ISSUE THREAD

**Issue by iandees** [developmentseed/observe#25] opened 2019-05-13 16:44 UTC
On a Pixel 3, Observe 0.1.7.

I added a new point and only gave it a name. When I pan around the map that pin flickers in and out of existence.

**Comment by geohacker** [comment] 2019-05-14 03:34
@iandees thanks for the ticket! possible to share a screengrab video/gif? We've not seen this behavior before. Does all map icons flicker or just the one you added?

**Comment by iandees** [comment] 2019-05-14 15:08
There isn't an easy way to do screen recording in Android, so here's a video capture of my screen from my Mac's web cam: [FlickeringMapInObserveApp.mov.zip](https://github.com/developmentseed/observe/files/3178488/FlickeringMapInObserveApp.mov.zip)

**Comment by geohacker** [comment] 2019-05-14 15:16
@iandees thanks so much for uploading the video! That looks pretty bad. This is likely something with react-native-mapbox-gl or just webgl. I could see this old ticket https://github.com/nitaliano/react-native-mapbox-gl/issues/614

cc @sethvincent @mojodna @batpad if you've any ideas.

**Comment by iandees** [comment] 2019-05-14 15:18
Also note that the pop-up text box that asks me to zoom in to edit flickers as well.

Unrelated: it bugs the crap out of me that Mapbox GL won't let me zoom in or out more than a couple zoom levels while pinching.

**Comment by geohacker** [comment] 2019-05-14 15:19
There's a newer, open ticket https://github.com/nitaliano/react-native-mapbox-gl/issues/1223 - which looks like it.

**Comment by sethvincent** [comment] 2019-11-05 00:29
I believe our recent switch to @react-native-mapbox-gl/maps has resolved this. We'll take another look and close this if true.

**Comment by iandees** [comment] 2019-11-05 01:44
Are there more recent builds I can try out?

**Comment by sethvincent** [comment] 2020-01-21 16:52
@iandees we just recently released v0.2.0-alpha that includes this change https://github.com/developmentseed/observe/releases

**Comment by geohacker** [comment] 2020-02-20 09:31
We haven't been able to reproduce this. Closing. Feel free to open in case anyone is able to reproduce.

**Closed by geohacker** 2020-02-20 09:31 UTC
