### ISSUE TITLE
Way is cleared after hitting "Back" on preset screen (Add Way)

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/observe#249] opened 2020-05-25 14:55 UTC
How to replicate:

- Enter "Add Way" mode
- Draw some points
- Hit "Tick"
- Hit "<-" at preset screen

The drawn line has been cleared, when it should be kept for further editing.

## iOS capture

![bug-2](https://user-images.githubusercontent.com/329694/82823803-1dcab000-9ea0-11ea-92aa-b2960a66100b.gif)

**Comment by geohacker** [comment] 2020-05-26 14:11
Tried this on the `edit-way-changesets` branch but not able to reproduce. cc @sethvincent

**Comment by sethvincent** [comment] 2020-05-30 00:39
I am also not able to reproduce now. It's weird because I know I saw this happening before.

My guess is that at some point the `resetWayEditing` action was being called when going back from the preset screen but after doing some testing it definitely isn't being called now.

I think we're good to close this.

**Closed** 2020-06-01 09:01 UTC
Labels: bug
